version: '3.8'

services:
  go-samba4:
    build: .
    container_name: go-samba4
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - samba4_data:/var/lib/go-samba4
      - ./config.toml:/etc/go-samba4/config.toml:ro
    environment:
      - SAMBA4_LDAP_PASS=secretpassword

volumes:
  samba4_data:
